-- Textos nuevos de las notificaciones y correo prendido (pedido de Juan,
-- 2026-10-01). El texto solo se cambia donde sigue el de fábrica: si el
-- admin ya lo editó a mano, se respeta. El correo se prende en todas.

UPDATE "NotificationTypeConfig" SET "messageTemplate" = '¡Vendiste con tu código en {marca}! Ganaste {monto} de comisión.' WHERE "key" = 'SALE_COMMISSION' AND "messageTemplate" = '¡Alguien compró con tu código en {marca}! Ganaste {monto} de comisión.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{marca} te quiere regalar "{producto}". Acéptala en Solicitar muestras y déjale tu dirección de envío.' WHERE "key" = 'SAMPLE_OFFERED' AND "messageTemplate" = '{marca} te quiere regalar una muestra de "{producto}" — revísalo en Muestras.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{marca} aprobó tu muestra de "{producto}" y pronto te la envía.' WHERE "key" = 'SAMPLE_APPROVED' AND "messageTemplate" = '{marca} aprobó tu solicitud de muestra: "{producto}" — te la envían pronto.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{marca} no puede enviarte la muestra de "{producto}" esta vez.{razon}' WHERE "key" = 'SAMPLE_REJECTED' AND "messageTemplate" = '{marca} no pudo enviarte la muestra de "{producto}" esta vez.{razon}';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{marca} te invitó a su programa de creadores. Revisa la invitación en Marketplace de marcas.' WHERE "key" = 'ENROLLMENT_INVITED_CREATOR' AND "messageTemplate" = '{marca} te invitó directo a unirte a su programa — revísalo en Marketplace de marcas.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '¡Ya eres parte de {marca}! Tu código está listo en Mis Códigos y Links.' WHERE "key" = 'ENROLLMENT_APPROVED_CREATOR' AND "messageTemplate" = '{marca} aprobó tu solicitud para unirte a su programa — ya puedes usar tu código.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{marca} no aprobó tu solicitud esta vez. Hay más marcas esperándote en el Marketplace.' WHERE "key" = 'ENROLLMENT_REJECTED_CREATOR' AND "messageTemplate" = '{marca} no aprobó tu solicitud para unirte a su programa esta vez.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Tienes {monto} en camino. Te lo transferimos en los próximos días.' WHERE "key" = 'PAYOUT_PENDING' AND "messageTemplate" = 'Tienes {monto} en camino — lo transferimos manualmente en los próximos días.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Te transferimos {monto}. Ya debería verse en tu cuenta.' WHERE "key" = 'PAYOUT_PAID' AND "messageTemplate" = 'Te pagamos {monto} — ya deberían verse en tu cuenta.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Te faltan unos pasos para completar tu perfil. Termínalo en "Empieza aquí" y las marcas te aprobarán más rápido.' WHERE "key" = 'ONBOARDING_REMINDER_1' AND "messageTemplate" = 'Te faltan algunos pasos para completar tu perfil de creador — no es obligatorio, pero ayuda a que las marcas confíen más rápido.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Aún te falta: {faltantes}. Lo terminas en un par de minutos desde "Empieza aquí".' WHERE "key" = 'ONBOARDING_REMINDER_2' AND "messageTemplate" = 'Todavía te falta terminar tu perfil de creador ({faltantes}) — cuando quieras, está en "Empieza aquí".';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Suspendimos tu cuenta. Si crees que es un error, escríbenos y lo revisamos.' WHERE "key" = 'ACCOUNT_SUSPENDED' AND "messageTemplate" = 'Tu cuenta fue suspendida. Contáctanos si crees que es un error.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '¡Tu cuenta está activa de nuevo! Ya puedes usar Marcolini con normalidad.' WHERE "key" = 'ACCOUNT_REACTIVATED' AND "messageTemplate" = 'Tu cuenta fue reactivada.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{marca} está en pausa por ahora y tu código no está generando ventas. Te avisamos apenas vuelva.' WHERE "key" = 'BRAND_PAUSED_CREATOR' AND "messageTemplate" = '{marca} está temporalmente no disponible — tu código no está generando ventas por ahora. Te avisamos apenas vuelva.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '¡{marca} volvió! Tu código funciona de nuevo; buen momento para compartirlo.' WHERE "key" = 'BRAND_RESUMED_CREATOR' AND "messageTemplate" = '¡{marca} ya está disponible de nuevo! Tu código vuelve a funcionar normal.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{creador} quiere probar "{producto}". Aprueba o rechaza la muestra en Muestras.' WHERE "key" = 'SAMPLE_REQUESTED' AND "messageTemplate" = '{creador} solicitó una muestra de "{producto}" — revísalo en Mi tienda → Muestras.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{creador} aceptó tu muestra de "{producto}". Ya está en Pedidos, lista para despachar.' WHERE "key" = 'SAMPLE_OFFER_ACCEPTED' AND "messageTemplate" = '{creador} aceptó tu oferta de muestra de "{producto}" — ya puedes ver el pedido en Pedidos.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{creador} quiere unirse a tu programa "{oferta}". Apruébalo en Creadores.' WHERE "key" = 'ENROLLMENT_REQUESTED_BRAND' AND "messageTemplate" = '{creador} solicitó unirse a tu programa "{oferta}" — revísalo en Creadores.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '{creador} no aceptó tu invitación esta vez.' WHERE "key" = 'ENROLLMENT_INVITATION_DECLINED' AND "messageTemplate" = '{creador} no aceptó tu invitación a unirse a tu programa.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = '¡Tu marca fue aprobada! Ya apareces en el marketplace y los creadores pueden unirse a tu programa.' WHERE "key" = 'BRAND_APPROVED' AND "messageTemplate" = '¡Tu marca fue aprobada! Ya apareces activa en el marketplace.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Tu marca no fue aprobada esta vez. Escríbenos si quieres saber por qué.' WHERE "key" = 'BRAND_REJECTED' AND "messageTemplate" = 'Tu marca no fue aprobada esta vez.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Tu corte está listo: {monto} en comisiones y tarifas. Fecha límite: {fecha}.' WHERE "key" = 'BRAND_CHARGE' AND "messageTemplate" = 'Nuevo corte: debes {monto} (comisiones, tarifa y premios de campañas). Fecha límite: {fecha}';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Te quedan {horas} para pagar tu corte de {monto}. Vence {fecha}.' WHERE "key" = 'BRAND_CHARGE_REMINDER' AND "messageTemplate" = 'Te quedan {horas} para pagar tu corte de {monto} — vence {fecha}';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Verificamos tu pago. ¡Gracias! Todo está al día.' WHERE "key" = 'BRAND_PAYMENT_VERIFIED' AND "messageTemplate" = 'Verificamos tu pago — tu marca está activa de nuevo.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'No pudimos verificar tu comprobante: {razon}. Sube uno nuevo en Configuración → Plan y facturación.' WHERE "key" = 'BRAND_PAYMENT_REJECTED' AND "messageTemplate" = 'Tu comprobante no se pudo verificar: {razon}. Sube uno nuevo desde Cuenta → Pago.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Tu acceso al panel está en pausa porque no hemos recibido tu pago. Tu tienda y los códigos de tus creadores siguen funcionando. Entra a Marcolini y sube tu comprobante antes del {fecha} para que el servicio no se desactive.' WHERE "key" = 'BRAND_LOCKED' AND "messageTemplate" = 'Tu cuenta quedó temporalmente inhabilitada por falta de pago verificado — sigues visible en el marketplace y los códigos de tus creadores siguen funcionando, pero no tienes acceso al panel. Sube tu comprobante en Cuenta → Pago para reactivarla. Si no se regulariza antes de {fecha}, tu servicio se desactiva por completo.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Última alerta: si no pagas antes del {fecha}, tu servicio se desactiva. Saldrás del marketplace y los códigos de tus creadores dejarán de funcionar.' WHERE "key" = 'BRAND_DEACTIVATION_REMINDER' AND "messageTemplate" = 'Última alerta: si no regularizas tu pago antes de {fecha}, tu servicio se desactiva por completo — desapareces del marketplace y los códigos de tus creadores dejan de funcionar. Sube tu comprobante en Cuenta → Pago.';
UPDATE "NotificationTypeConfig" SET "messageTemplate" = 'Tu servicio está desactivado por falta de pago: no apareces en el marketplace y los códigos de tus creadores no registran ventas. Debes {monto}. Sube tu comprobante y lo reactivamos apenas lo verifiquemos.' WHERE "key" = 'BRAND_DEACTIVATED' AND "messageTemplate" = 'Tu servicio quedó desactivado por falta de pago: desapareciste del marketplace y los códigos de tus creadores ya no atribuyen ventas. Sigues debiendo {monto}. Sube tu comprobante en Cuenta → Pago — apenas lo verifiquemos, se reactiva todo automáticamente.';

UPDATE "NotificationTypeConfig" SET "channelEmail" = true WHERE "key" IN ('SALE_COMMISSION', 'SAMPLE_OFFERED', 'SAMPLE_APPROVED', 'SAMPLE_REJECTED', 'ENROLLMENT_INVITED_CREATOR', 'ENROLLMENT_APPROVED_CREATOR', 'ENROLLMENT_REJECTED_CREATOR', 'PAYOUT_PENDING', 'PAYOUT_PAID', 'ONBOARDING_REMINDER_1', 'ONBOARDING_REMINDER_2', 'ACCOUNT_SUSPENDED', 'ACCOUNT_REACTIVATED', 'BRAND_PAUSED_CREATOR', 'BRAND_RESUMED_CREATOR', 'SAMPLE_REQUESTED', 'SAMPLE_OFFER_ACCEPTED', 'ENROLLMENT_REQUESTED_BRAND', 'ENROLLMENT_INVITATION_DECLINED', 'BRAND_APPROVED', 'BRAND_REJECTED', 'BRAND_CHARGE', 'BRAND_CHARGE_REMINDER', 'BRAND_PAYMENT_VERIFIED', 'BRAND_PAYMENT_REJECTED', 'BRAND_LOCKED', 'BRAND_DEACTIVATION_REMINDER', 'BRAND_DEACTIVATED');
